[package]
name = "sftp-tube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clipboard-win = "5.3.0"
rpassword = "7.3.1"
ssh2 = "0.9.4"
